# Generated by Django 4.1.3 on 2022-12-06 21:48

import Subscriptions.models
import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_length', models.PositiveIntegerField()),
                ('price', models.FloatField(validators=[Subscriptions.models.validate_positive])),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('valid_date', models.DateField()),
                ('cancelled', models.BooleanField()),
                ('card_number', creditcards.models.CardNumberField(max_length=25)),
                ('card_expiry', creditcards.models.CardExpiryField()),
                ('card_security_code', creditcards.models.SecurityCodeField(max_length=4)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('plan_month_length', models.PositiveIntegerField()),
                ('paid_card_number', creditcards.models.CardNumberField(max_length=25, null=True)),
                ('paid', models.BooleanField()),
                ('paid_at', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
