# Generated by Django 4.1.3 on 2022-12-06 21:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import phonenumber_field.modelfields
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amname', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='ClassDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_id', models.PositiveIntegerField()),
                ('course_id', models.PositiveIntegerField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('current_enrolment', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=200)),
                ('studio_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='className',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classNames', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='coachName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachNames', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='CourseKeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('address', models.CharField(max_length=180)),
                ('geographical_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[A-Z]{1}[0-9]{1}[A-Z]{1}\\s*[0-9]{1}[A-Z]{1}[0-9]{1}$', 'Invalid postal code')])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('amenities', models.ManyToManyField(blank=True, editable=False, null=True, to='Studios.aname')),
                ('classes', models.ManyToManyField(blank=True, editable=False, null=True, to='Studios.classname')),
                ('coaches', models.ManyToManyField(blank=True, editable=False, null=True, to='Studios.coachname')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='studios')),
                ('studio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_images', to='Studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dropped', models.BooleanField(default=False)),
                ('enrollDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Studios.classdate')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userenroll', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DropDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Studios.enroll')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdrop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='start')),
                ('end_time', models.DateTimeField(verbose_name='end')),
                ('capacity', models.PositiveIntegerField()),
                ('times', recurrence.fields.RecurrenceField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(to='Studios.coursekeyword')),
                ('studio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_class', to='Studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Amenitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=180)),
                ('quantity', models.PositiveIntegerField()),
                ('studio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_amenities', to='Studios.studio')),
            ],
        ),
    ]
